# Generated by Django 5.0.5 on 2024-05-06 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('endereco', models.TextField()),
                ('telefone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('data_nascimento', models.DateField()),
                ('crm', models.CharField(max_length=30)),
                ('id_especialidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medico.especialidade')),
            ],
        ),
    ]
